logging:
  level:
    root: info
  config: classpath:logback-spring.xml

mqtt:
  username: test
  password: test
  wait_time: 10000
  interval: 3000
  port: 1883
  enable_clean_session: true
  enable_ssl: false
  caCertFile: cert/server/ca.crt
  serverCertFile: cert/server/server.crt
  keyFile: cert/server/pkcs8_server.key

spring:
  data:
    redis:
      host: 192.168.2.219
      port: 59504
      timeout: 5000ms
      password: NaviCloud1234
      lettuce:
        pool:
          max-active: 20 # 最大活跃连接数
          max-idle: 10   # 最大空闲连接数
          min-idle: 5    # 最小空闲连接数
          max-wait: 3000ms # 获取连接的最大等待时间


rocketmq:
  name-server: 192.168.2.219:9876
  producer:
    group: mqtt-relay-producer
    relay:
      topic: mqtt_publish
      retries: 3
  consumer:
    group: mqtt-relay-consumer
    relay:
      topic: mqtt_command
      retries: 3




mqttwk:
  broker:
    id: mqttwk  # Broker唯一标识
#    host: 127.0.0.1  # 服务启动的IP
    port: 1883  # 端口号, 默认8885
    username: User_X7#B2rJ
    password: 8v$JrT!dQ9@LmX3
#    cluster-on: false  # 是否开启集群模式, 默认false
    websocket-port: 9995  # WebSocket端口号, 默认9995
    websocket-enabled: true  # WebSocket是否启用
    websocket-path: /mqtt  # WebSocket访问路径, 默认/mqtt
    mqttPasswordMust: true
    ssl-enabled: true  # SSL是否启用
    keep-alive: 120  # 心跳时间(秒), 默认60秒
    session-timeout: 120
    use-epoll: false  # 是否开启Epoll模式, 默认关闭
    so-backlog: 511  # Socket参数, 存放已完成三次握手请求的队列最大长度, 默认511长度
    so-keep-alive: true  # 是否开启心跳保活机制, 默认开启
    bossGroup-nThreads: 1  # bossGroup线程数, 默认4
    workerGroup-nThreads: 16  # workerGroup线程数, 默认20
    amqp-enable: false #是否开启消息队列转发, 当前实现为rocketMQ
    session-storage-type: caffeine # 存储类型: caffeine 或 redis，默认是 caffeine
